review
nastiesdi/nastiesdi-add_task--n-name--i pull request #21
Opened 2019-12-18 19:40 UTC by nastiesdi

I hope it is okey)

2019-12-18 21:19 UTC, GubinAlexander requested changes

2019-12-18 21:19 UTC, GubinAlexander commented on helpers/checker.py
> +    return bool(re.compile(r'^(?=.*[0-9].*)(?=.*[a-z].*)(?=.*[A-Z].*)[0-9a-zA-Z]{8,}$').match(password))
переписать без bool

2019-12-18 21:27 UTC, GubinAlexander requested changes

2019-12-18 21:27 UTC, GubinAlexander commented on helpers/decorators.py
> +    def check_login(manager, input):
self, какой manager

2019-12-18 21:27 UTC, GubinAlexander commented on manager.py
> +        self.logger.info(f'user show all devs')
какой смысл здесь в f string?

2019-12-18 21:27 UTC, GubinAlexander commented on manager.py
> +        self.logger.info(f'user show all devs')
и во всех остальных местах?

2019-12-18 21:27 UTC, GubinAlexander commented on src/dev.py
> +            raise Exception('Password is not valid')    # TODO
А здесь почему не поменяла?

2019-12-19 14:10 UTC, nastiesdi commented
Add second commit

2019-12-19 19:03 UTC, merged